# Generated by Django 4.2.2 on 2023-07-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Exempt"),
                            (2, "Beta"),
                            (3, "Trial"),
                            (4, "Active"),
                            (5, "Cancelled"),
                            (6, "Trial Expired"),
                        ],
                        db_index=True,
                        default=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
