# Generated by Django 4.2.3 on 2023-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_travelfriend_delete_familymember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelfriend",
            options={"verbose_name": "compagno di viaggio", "verbose_name_plural": "compagni di viaggio"},
        ),
        migrations.AlterField(
            model_name="travelfriend",
            name="birthdate",
            field=models.DateField(),
        ),
    ]
